### ISSUE TITLE
Would you please introduce the adjust() function in timer class

### ISSUE THREAD

**Issue by dourgulf** [pockethook/player#3]
How this adjust algorithm work.
Is there any reference about this algorithm?

**Comment by pockethook** [comment]
Have a look at https://en.wikipedia.org/wiki/PID_controller. `P_, I_, D_` were tweaked on my machine to minimize error in `Timer::wait`. The PID controller isn't really necessary, as the wait error is normally quite small and this isn't meant to be a bullet-proof player. The simplest way to remove the PID controller is to set `P_, I_, D_` to zero.

**Comment by dourgulf** [comment]
3Q(sorry for my delay)
